// Generated by scripts/build_recovery_hook.mjs. Do not edit manually.
var __defProp = Object.defineProperty;
var __defProps = Object.defineProperties;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropDescs = Object.getOwnPropertyDescriptors;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getOwnPropSymbols = Object.getOwnPropertySymbols;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __propIsEnum = Object.prototype.propertyIsEnumerable;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __spreadValues = (a, b) => {
  for (var prop in b || (b = {}))
    if (__hasOwnProp.call(b, prop))
      __defNormalProp(a, prop, b[prop]);
  if (__getOwnPropSymbols)
    for (var prop of __getOwnPropSymbols(b)) {
      if (__propIsEnum.call(b, prop))
        __defNormalProp(a, prop, b[prop]);
    }
  return a;
};
var __spreadProps = (a, b) => __defProps(a, __getOwnPropDescs(b));
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/core/debtRecovery.js
var debtRecovery_exports = {};
__export(debtRecovery_exports, {
  buildDebtRecoveryRenewal: () => buildDebtRecoveryRenewal,
  getRecoveryAgeDays: () => getRecoveryAgeDays,
  getRenewedLoanNumber: () => getRenewedLoanNumber,
  isDebtRecoveryLoan: () => isDebtRecoveryLoan,
  isRecoveredLoan: () => isRecoveredLoan,
  isRolledOverLoan: () => isRolledOverLoan
});
module.exports = __toCommonJS(debtRecovery_exports);

// src/core/financialRecords.js
var getFinancialTimestamp = (value) => {
  if (value instanceof Date) return value.getTime();
  if (!value) return NaN;
  let text = String(value).trim();
  if (/^\d{4}-\d{2}-\d{2}/.test(text)) {
    const day = text.slice(0, 10);
    const date = /* @__PURE__ */ new Date(`${day}T00:00:00Z`);
    if (!Number.isFinite(date.getTime()) || date.toISOString().slice(0, 10) !== day) return NaN;
  }
  if (/^\d{4}-\d{2}-\d{2}$/.test(text)) text += "T00:00:00+03:00";
  else if (/^\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}/.test(text) && !/(Z|[+-]\d{2}:?\d{2})$/i.test(text)) text = text.replace(" ", "T") + "Z";
  return new Date(text).getTime();
};
var financialCents = (value, label = "Amount") => {
  const amount = value === null || value === void 0 || value === "" ? 0 : Number(value);
  const cents = Math.round(amount * 100);
  if (value != null && !["number", "string"].includes(typeof value) || !Number.isFinite(amount) || amount < 0 || !Number.isSafeInteger(cents) || Math.abs(amount * 100 - cents) > 1e-5) throw new Error(`${label} requires a valid non-negative amount to two decimals`);
  return cents;
};
var selectFinancialRecords = (records = [], { cutoff, fields = ["date", "effective_date", "created"] } = {}) => {
  const latest = /* @__PURE__ */ new Map();
  const anonymous = [];
  for (const record of records) {
    if (!(record == null ? void 0 : record.id)) {
      anonymous.push(record);
      continue;
    }
    const prior = latest.get(record.id);
    if (!prior || getFinancialTimestamp(record.updated || record.created) > getFinancialTimestamp(prior.updated || prior.created)) latest.set(record.id, record);
    else if (prior !== record && JSON.stringify(prior) !== JSON.stringify(record) && !(getFinancialTimestamp(prior.updated || prior.created) > getFinancialTimestamp(record.updated || record.created))) throw new Error(`Conflicting financial record ${record.id}`);
  }
  const limit = cutoff ? getFinancialTimestamp(cutoff) : Infinity;
  if (cutoff && !Number.isFinite(limit)) throw new Error("Invalid financial cutoff");
  return [...latest.values(), ...anonymous].filter((record) => {
    if ((record == null ? void 0 : record.is_reversed) || (record == null ? void 0 : record.status) === "reversed") return false;
    const value = fields.map((field) => record == null ? void 0 : record[field]).find(Boolean);
    if (!value) {
      if (record.id && cutoff && fields.length) throw new Error(`Effective financial date unavailable on ${record.id}`);
      return true;
    }
    const timestamp = getFinancialTimestamp(value);
    if (!Number.isFinite(timestamp)) throw new Error(`Invalid financial date on ${record.id || "record"}`);
    return timestamp <= limit;
  });
};

// src/core/loanInstallments.js
var relationId = (value) => typeof value === "string" ? value : (value == null ? void 0 : value.id) || "";
var amountValue = (value) => {
  const amount = Number(value);
  if (value === null || value === void 0 || value === "" || !["number", "string"].includes(typeof value) || !Number.isFinite(amount) || amount < 0 || !Number.isSafeInteger(Math.round(amount * 100))) {
    throw new Error("Installment requires a valid non-negative amount");
  }
  return amount;
};
var normalizeLoanSchedules = (schedules = []) => {
  const installments = /* @__PURE__ */ new Map();
  selectFinancialRecords(schedules, { fields: [] }).forEach((schedule, index) => {
    const loan = relationId(schedule.loan);
    const number = Number(schedule.installment_no);
    const key = loan && Number.isInteger(number) && number > 0 ? `${loan}:${number}` : `row:${schedule.id || index}`;
    const prior = installments.get(key);
    if (prior) {
      const time = getFinancialTimestamp(schedule.updated || schedule.created) || 0;
      const priorTime = getFinancialTimestamp(prior.updated || prior.created) || 0;
      if (time === priorTime && (Number(schedule.amount) !== Number(prior.amount) || getFinancialTimestamp(schedule.due_date) !== getFinancialTimestamp(prior.due_date) || Boolean(schedule.penalty_waived) !== Boolean(prior.penalty_waived))) {
        throw new Error(`Conflicting repayment installment ${key}`);
      }
      if (time < priorTime || time === priorTime && String(schedule.id) < String(prior.id)) return;
    }
    installments.set(key, schedule);
  });
  const ordered = [...installments.values()].sort((a, b) => relationId(a.loan).localeCompare(relationId(b.loan)) || (Number(a.installment_no) || 0) - (Number(b.installment_no) || 0) || getFinancialTimestamp(a.due_date) - getFinancialTimestamp(b.due_date));
  const totals = /* @__PURE__ */ new Map();
  return ordered.map((schedule, index) => {
    var _a;
    const key = relationId(schedule.loan) || `anonymous:${index}`;
    const previous = totals.get(key) || 0;
    const next = previous + amountValue(schedule.amount) * 100;
    if (!Number.isSafeInteger(Math.round(next))) throw new Error("Scheduled total exceeds the supported monetary range");
    totals.set(key, next);
    const amount = (Math.round(next) - Math.round(previous)) / 100;
    if (amount > 0 && !Number.isFinite(getFinancialTimestamp(schedule.due_date))) throw new Error(`Installment due date unavailable on ${schedule.id || "schedule"}`);
    const paid = Math.min(amount, Math.round(amountValue((_a = schedule.paid) != null ? _a : 0) * 100) / 100);
    return __spreadProps(__spreadValues({}, schedule), { amount, paid });
  });
};

// src/core/loanPenalty.js
var toDate = (value) => new Date(getFinancialTimestamp(value));
var startOfLocalDay = (date = /* @__PURE__ */ new Date()) => {
  const value = toDate(date);
  if (Number.isNaN(value.getTime())) return null;
  return new Date(Math.floor((value.getTime() + 108e5) / 864e5) * 864e5 - 108e5);
};
var endOfLocalDay = (date = /* @__PURE__ */ new Date()) => {
  const value = toDate(date);
  if (Number.isNaN(value.getTime())) return null;
  return new Date(startOfLocalDay(value).getTime() + 864e5 - 1);
};
var sortSchedules = (schedules = []) => schedules.slice().sort((a, b) => {
  const installmentDiff = (Number(a.installment_no) || 0) - (Number(b.installment_no) || 0);
  if (installmentDiff !== 0) return installmentDiff;
  return toDate(a.due_date || 0) - toDate(b.due_date || 0);
});
var sortRepayments = (repayments = []) => repayments.slice().sort((a, b) => toDate(a.date || a.created || 0) - toDate(b.date || b.created || 0));
var getContractPaymentDate = (record) => (record == null ? void 0 : record.date) || (record == null ? void 0 : record.effective_date) || (record == null ? void 0 : record.created) || /* @__PURE__ */ new Date();
var getRepaymentPrincipalAmount = (repayment) => Math.max(
  0,
  (Number(repayment == null ? void 0 : repayment.amount) || 0) - (Number(repayment == null ? void 0 : repayment.fine_amount) || 0)
);
var getContractSettlementAmount = (record) => {
  if ((record == null ? void 0 : record.settlement_kind) === "balance_off") return Math.max(0, Number(record.amount) || 0);
  return getRepaymentPrincipalAmount(record);
};
var calculateLoanPenaltyState = ({
  schedules = [],
  repayments = [],
  settlements = [],
  penaltyAmount = 0,
  referenceDate = /* @__PURE__ */ new Date(),
  useRecordedSchedulePaid = true
} = {}) => {
  repayments = selectFinancialRecords(repayments, { cutoff: referenceDate });
  settlements = selectFinancialRecords(settlements, { cutoff: referenceDate, fields: ["effective_date", "date", "created"] });
  schedules = normalizeLoanSchedules(schedules);
  const penaltyCents = financialCents(penaltyAmount, "Penalty");
  schedules.forEach((schedule) => {
    if (Number(schedule.amount) > 0 && !Number.isFinite(getFinancialTimestamp(schedule.due_date))) throw new Error(`Installment due date unavailable on ${schedule.id || "schedule"}`);
  });
  const orderedSchedules = sortSchedules(schedules).map((schedule) => ({
    schedule,
    amount: financialCents(schedule.amount, "Installment"),
    paid: 0,
    completedAt: null
  }));
  sortRepayments([
    ...repayments,
    ...settlements.filter((settlement) => (settlement == null ? void 0 : settlement.status) !== "reversed").map((settlement) => __spreadProps(__spreadValues({}, settlement), {
      date: settlement.effective_date || settlement.date || settlement.created,
      settlement_kind: "balance_off"
    }))
  ]).forEach((repayment) => {
    let remainingPayment = financialCents(getContractSettlementAmount(repayment), "Contract receipt");
    const paidAt = toDate(getContractPaymentDate(repayment));
    for (const item of orderedSchedules) {
      if (remainingPayment <= 0) break;
      const openAmount = Math.max(0, item.amount - item.paid);
      if (openAmount <= 0) continue;
      const applied = Math.min(openAmount, remainingPayment);
      item.paid += applied;
      remainingPayment -= applied;
      if (item.paid >= item.amount && !item.completedAt) item.completedAt = paidAt;
    }
  });
  if (useRecordedSchedulePaid) {
    orderedSchedules.forEach((item) => {
      const recordedPaid = financialCents(item.schedule.paid, "Recorded installment payment");
      if (recordedPaid > item.paid) item.paid = Math.min(item.amount, recordedPaid);
    });
  }
  const today = startOfLocalDay(referenceDate);
  const scheduleStates = orderedSchedules.map((item) => {
    const dueStart = startOfLocalDay(item.schedule.due_date);
    const dueEnd = endOfLocalDay(item.schedule.due_date);
    const dueDatePassed = Boolean(dueStart && today && dueStart < today);
    const completedLate = Boolean(item.completedAt && dueEnd && item.completedAt > dueEnd);
    const stillUnpaidAfterDue = item.paid < item.amount && dueDatePassed;
    const penaltyGenerated = Boolean(
      !item.schedule.penalty_waived && penaltyAmount > 0 && dueDatePassed && (completedLate || stillUnpaidAfterDue)
    );
    return {
      schedule: item.schedule,
      paid: item.paid / 100,
      remainingPrincipal: Math.max(0, item.amount - item.paid) / 100,
      completedAt: item.completedAt,
      penaltyGenerated,
      penaltyAmount: ((penaltyGenerated ? penaltyCents : 0) + financialCents(item.schedule.carried_fine, "Carried fine")) / 100
    };
  });
  const generatedFineTotal = scheduleStates.reduce((sum, item) => sum + financialCents(item.penaltyAmount), 0) / 100;
  const fineCollected = repayments.reduce((sum, repayment) => sum + financialCents(repayment.fine_amount, "Collected fine"), 0) / 100;
  const principalPaid = [
    ...repayments,
    ...settlements.filter((settlement) => (settlement == null ? void 0 : settlement.status) !== "reversed").map((settlement) => __spreadProps(__spreadValues({}, settlement), { settlement_kind: "balance_off" }))
  ].reduce((sum, repayment) => sum + financialCents(getContractSettlementAmount(repayment)), 0) / 100;
  return {
    scheduleStates,
    generatedFineTotal,
    fineCollected,
    outstandingFine: Math.max(0, financialCents(generatedFineTotal) - financialCents(fineCollected)) / 100,
    principalPaid
  };
};

// src/core/repaymentAllocation.js
var asAmount = (value) => Math.max(0, Number(value) || 0);
var getLoanPrincipalAmount = (loan) => {
  const approved = asAmount(loan == null ? void 0 : loan.approved_amount);
  if (approved > 0) return approved;
  const applied = asAmount(loan == null ? void 0 : loan.amount_applied);
  if (applied > 0) return applied;
  const liability = asAmount(loan == null ? void 0 : loan.total_liability);
  const interest = asAmount(loan == null ? void 0 : loan.interest_amount);
  return Math.max(0, liability - interest);
};
var getLoanInterestAmount = (loan) => {
  const storedInterest = asAmount(loan == null ? void 0 : loan.interest_amount);
  if (storedInterest > 0) return storedInterest;
  const principal = getLoanPrincipalAmount(loan);
  const liability = asAmount(loan == null ? void 0 : loan.total_liability);
  if (liability > principal) return liability - principal;
  const interestRate = asAmount(loan == null ? void 0 : loan.interest_rate);
  return principal > 0 && interestRate > 0 ? principal * (interestRate / 100) : 0;
};
var getLoanLiabilityAmount = (loan) => {
  const principal = getLoanPrincipalAmount(loan);
  const interest = getLoanInterestAmount(loan);
  const storedLiability = asAmount(loan == null ? void 0 : loan.total_liability);
  return Math.max(storedLiability, principal + interest);
};
var getRepaymentContractAmount = (repayment) => {
  const amount = asAmount(repayment == null ? void 0 : repayment.amount);
  const fine = Math.min(amount, asAmount(repayment == null ? void 0 : repayment.fine_amount));
  return amount - fine;
};
var getSettlementContractAmount = (settlement) => {
  if (!settlement || settlement.status === "reversed") return 0;
  return asAmount(settlement.amount);
};

// src/core/loanPortfolio.js
var getLoanAtCutoff = (loan, { asOf, loans = [] } = {}) => {
  var _a;
  if (!loan || !asOf) return loan;
  const cutoff = getFinancialTimestamp(asOf);
  const disbursedAt = getFinancialTimestamp(loan.disbursement_date);
  if (!Number.isFinite(cutoff)) throw new Error("Invalid OLB cutoff");
  if (!Number.isFinite(disbursedAt) || disbursedAt > cutoff) return null;
  let result = loan;
  if (loan.status === "written_off") {
    const writtenOffAt = getFinancialTimestamp(loan.written_off_at);
    if (!Number.isFinite(writtenOffAt)) throw new Error(`Write-off date unavailable for ${loan.loan_no || loan.id}`);
    if (writtenOffAt <= cutoff) return null;
    result = __spreadProps(__spreadValues({}, result), { status: "disbursed" });
  }
  if (loan.renewed_to) {
    const targetId = typeof loan.renewed_to === "string" ? loan.renewed_to : loan.renewed_to.id;
    const target = loans.find((item) => item.id === targetId) || ((_a = loan.expand) == null ? void 0 : _a.renewed_to);
    const renewalDate = getFinancialTimestamp((target == null ? void 0 : target.renewal_date) || (target == null ? void 0 : target.disbursement_date));
    if (!Number.isFinite(renewalDate)) throw new Error(`Renewal date unavailable for ${loan.loan_no || loan.id}`);
    if (renewalDate <= cutoff) return null;
    result = __spreadProps(__spreadValues({}, result), { status: "disbursed", renewed_to: "" });
  }
  return result;
};
var isDisbursedLoanRecord = (loan) => Boolean(loan == null ? void 0 : loan.disbursement_date) && ["disbursed", "approved", "partial_approved", "completed", "closed"].includes(loan == null ? void 0 : loan.status);
var isCollectibleLoanRecord = (loan) => Boolean(loan == null ? void 0 : loan.disbursement_date) && ["disbursed", "approved", "partial_approved"].includes(loan == null ? void 0 : loan.status);
var isWrittenOffLoanRecord = (loan) => (loan == null ? void 0 : loan.status) === "written_off";
var calculateLoanBalanceBreakdown = ({
  loan,
  repayments = [],
  settlements = [],
  schedules = [],
  penaltyAmount = 0,
  includeOutstandingFines = true,
  referenceDate = /* @__PURE__ */ new Date(),
  useRecordedSchedulePaid = false,
  asOf,
  loans = []
} = {}) => {
  const empty = { liability: 0, contractPaid: 0, contractBalance: 0, outstandingFine: 0, outstanding: 0 };
  loan = getLoanAtCutoff(loan, { asOf, loans });
  if (!loan || !isDisbursedLoanRecord(loan) || isWrittenOffLoanRecord(loan) || loan.renewed_to) return empty;
  const cutoff = asOf || referenceDate;
  const disbursedAt = getFinancialTimestamp(loan.disbursement_date);
  if (!Number.isFinite(disbursedAt)) throw new Error(`Invalid disbursement date on ${loan.id || "loan"}`);
  if (disbursedAt > getFinancialTimestamp(cutoff)) return empty;
  for (const field of ["approved_amount", "amount_applied", "interest_amount", "total_liability"]) financialCents(loan[field], `Loan ${field}`);
  repayments = selectFinancialRecords(repayments, { cutoff });
  settlements = selectFinancialRecords(settlements, { cutoff, fields: ["effective_date", "date", "created"] });
  const liability = financialCents(getLoanLiabilityAmount(loan), "Loan liability");
  if (liability <= 0) throw new Error(`Disbursed liability unavailable for ${loan.loan_no || loan.id}`);
  const contractPaid = repayments.reduce((sum, repayment) => {
    const amount = financialCents(repayment.amount, "Receipt");
    if (amount <= 0) throw new Error(`Receipt amount unavailable on ${repayment.id || "repayment"}`);
    const fine2 = financialCents(repayment.fine_amount, "Collected fine");
    if (fine2 > amount) throw new Error(`Fine exceeds receipt on ${repayment.id || "repayment"}`);
    return sum + amount - fine2;
  }, 0) + settlements.reduce((sum, settlement) => {
    const amount = financialCents(settlement.amount, "Balance-off");
    if (amount <= 0) throw new Error(`Balance-off amount unavailable on ${settlement.id || "settlement"}`);
    return sum + amount;
  }, 0);
  const contractBalance = Math.max(0, liability - contractPaid);
  if (!Number.isSafeInteger(contractPaid)) throw new Error("Contract payment total exceeds the supported monetary range");
  const penaltyState = calculateLoanPenaltyState({
    schedules,
    repayments,
    settlements,
    penaltyAmount,
    referenceDate: cutoff,
    useRecordedSchedulePaid
  });
  const fine = includeOutstandingFines ? financialCents(penaltyState.outstandingFine) : 0;
  return {
    liability: liability / 100,
    contractPaid: contractPaid / 100,
    contractBalance: contractBalance / 100,
    outstandingFine: fine / 100,
    outstanding: (contractBalance + fine) / 100
  };
};
var calculateLoanOutstandingBalance = (options) => calculateLoanBalanceBreakdown(options).outstanding;

// src/core/repaymentSchedule.js
var toValidDate = (value) => {
  if (!value) return null;
  const date = new Date(typeof value === "string" ? value.replace(" ", "T") : value);
  return Number.isNaN(date.getTime()) ? null : date;
};
var getRepaymentScheduleAnchorDate = (loan) => toValidDate(loan == null ? void 0 : loan.renewal_date) || toValidDate(loan == null ? void 0 : loan.disbursement_date) || toValidDate(loan == null ? void 0 : loan.application_date) || toValidDate(loan == null ? void 0 : loan.created) || /* @__PURE__ */ new Date();
var getLoanGracePeriodMonths = (loan) => {
  if ((loan == null ? void 0 : loan.type) !== "farming") return 0;
  const gracePeriod = Number.parseInt(loan == null ? void 0 : loan.grace_period_months, 10);
  return Number.isInteger(gracePeriod) && gracePeriod > 0 ? gracePeriod : 0;
};
var addMonthsPreservingDay = (dateInput, monthsToAdd) => {
  const source = toValidDate(dateInput) || /* @__PURE__ */ new Date();
  const targetDay = source.getDate();
  const dueDate = new Date(source);
  dueDate.setDate(1);
  dueDate.setMonth(dueDate.getMonth() + monthsToAdd);
  const lastDayOfTargetMonth = new Date(
    dueDate.getFullYear(),
    dueDate.getMonth() + 1,
    0
  ).getDate();
  dueDate.setDate(Math.min(targetDay, lastDayOfTargetMonth));
  return dueDate;
};
var getRepaymentScheduleDueDate = (loan, installmentNo) => {
  const installment = Number.parseInt(installmentNo, 10);
  if (!Number.isInteger(installment) || installment < 1) return null;
  const gracePeriod = getLoanGracePeriodMonths(loan);
  const firstDueMonth = gracePeriod || 1;
  return addMonthsPreservingDay(
    getRepaymentScheduleAnchorDate(loan),
    firstDueMonth + installment - 1
  );
};
var getLoanFinalDueDate = (loan) => {
  const period = Number.parseInt(loan == null ? void 0 : loan.period, 10);
  return Number.isInteger(period) && period > 0 ? getRepaymentScheduleDueDate(loan, period) : null;
};

// src/core/distressUnit.js
var toValidDate2 = (value) => {
  if (!value) return null;
  const date = value instanceof Date ? value : new Date(String(value).replace(" ", "T"));
  return Number.isNaN(date.getTime()) ? null : date;
};
var startOfDay = (value) => {
  const date = toValidDate2(value);
  if (!date) return null;
  date.setHours(0, 0, 0, 0);
  return date;
};
var getLoanEndDate = (loan) => {
  return getLoanFinalDueDate(loan);
};
var isDistressUnitLoan = (loan, {
  outstandingBalance = 0,
  referenceDate = /* @__PURE__ */ new Date()
} = {}) => {
  if (!isCollectibleLoanRecord(loan)) return false;
  const endDate = startOfDay(getLoanEndDate(loan));
  const today = startOfDay(referenceDate);
  if (!endDate || !today) return false;
  return endDate < today && Number(outstandingBalance) > 0.01;
};

// src/core/debtRecovery.js
var money = (value) => Math.round((Number(value) || 0) * 100) / 100;
var businessDay = (value) => {
  const date = new Date(typeof value === "string" ? value.replace(" ", "T") : value);
  return Number.isNaN(date.getTime()) ? NaN : Math.floor((date.getTime() + 3 * 36e5) / 864e5);
};
var getRenewedLoanNumber = (loanNo = "") => {
  const normalized = String(loanNo || "").trim() || "LN";
  const match = normalized.match(/^(.*)-R(\d+)$/i);
  if (!match) return `${normalized}-R1`;
  return `${match[1]}-R${Number(match[2]) + 1}`;
};
var isRolledOverLoan = (loan) => {
  var _a;
  return Boolean(((_a = loan == null ? void 0 : loan.renewed_to) == null ? void 0 : _a.id) || (loan == null ? void 0 : loan.renewed_to));
};
var getRecoveryAgeDays = (loan, referenceDate = /* @__PURE__ */ new Date()) => {
  const recoveryStart = getLoanGracePeriodMonths(loan) > 0 ? getRepaymentScheduleDueDate(loan, 1) : (loan == null ? void 0 : loan.renewal_date) || (loan == null ? void 0 : loan.disbursement_date);
  return businessDay(referenceDate) - businessDay(recoveryStart);
};
var isDebtRecoveryLoan = (loan, {
  repayments = [],
  settlements = [],
  schedules = [],
  referenceDate = /* @__PURE__ */ new Date()
} = {}) => {
  if (!isCollectibleLoanRecord(loan) || getRecoveryAgeDays(loan, referenceDate) < 90) return false;
  if (!Number.isFinite(getRecoveryAgeDays(loan, referenceDate))) return false;
  if (!(Number(loan.total_liability) > 0)) return false;
  if (repayments.some((record) => !record.is_reversed && Number(record.amount) > 0)) return false;
  if (settlements.some((record) => record.status !== "reversed" && Number(record.amount) > 0)) return false;
  return !schedules.some((record) => Number(record.paid) > 0);
};
var isRecoveredLoan = (loan, {
  repayments = [],
  settlements = [],
  schedules = [],
  penaltyAmount = 500,
  referenceDate = /* @__PURE__ */ new Date()
} = {}) => {
  var _a, _b, _c;
  const legacyInPlaceRenewal = Boolean((_a = loan == null ? void 0 : loan.renewal_summary) == null ? void 0 : _a.renewal_id) && !(((_b = loan == null ? void 0 : loan.renewed_from) == null ? void 0 : _b.id) || (loan == null ? void 0 : loan.renewed_from));
  if (!isDisbursedLoanRecord(loan) || loan.written_off_at || isRolledOverLoan(loan) || legacyInPlaceRenewal) return false;
  const liability = getLoanLiabilityAmount(loan);
  if (!(liability > 0) || !Number.isFinite(businessDay(loan.disbursement_date))) return false;
  const payments = repayments.filter((row) => !row.is_reversed && Number(row.amount) > 0);
  const balanceOffs = settlements.filter((row) => row.status !== "reversed" && Number(row.amount) > 0);
  const paymentDays = [
    ...payments.map((row) => businessDay(row.date || row.created)),
    ...balanceOffs.map((row) => businessDay(row.effective_date || row.date || row.created))
  ];
  if (!paymentDays.length || paymentDays.some((day) => !Number.isFinite(day) || day > businessDay(referenceDate))) return false;
  const renewedFromRecovery = Boolean((_c = loan.renewal_summary) == null ? void 0 : _c.renewal_id) && Number.isFinite(businessDay(loan.renewal_date));
  const firstPaymentDay = Math.min(...paymentDays);
  const paidDirectlyFromRecovery = firstPaymentDay - businessDay(loan.disbursement_date) >= 90;
  if (!renewedFromRecovery && !paidDirectlyFromRecovery) return false;
  const contractPaid = payments.reduce((sum, row) => sum + getRepaymentContractAmount(row), 0) + balanceOffs.reduce((sum, row) => sum + getSettlementContractAmount(row), 0);
  if (money(contractPaid) < money(liability)) return false;
  const period = Number(loan.period);
  if (!Number.isInteger(period) || period < 1) return false;
  const installmentNumbers = new Set(schedules.map((row) => Number(row.installment_no)));
  if (schedules.length !== period || schedules.some((row) => !Number.isFinite(businessDay(row.due_date))) || !Array.from({ length: period }, (_, index) => index + 1).every((number) => installmentNumbers.has(number))) return false;
  return money(calculateLoanOutstandingBalance({
    loan,
    repayments: payments,
    settlements: balanceOffs,
    schedules,
    penaltyAmount,
    referenceDate
  })) === 0;
};
var buildDebtRecoveryRenewal = ({
  loan,
  repayments = [],
  settlements = [],
  schedules = [],
  penaltyAmount = 500,
  period,
  interestRate: requestedInterestRate,
  renewalDate: requestedRenewalDate,
  finalDueDate: requestedFinalDueDate,
  referenceDate = /* @__PURE__ */ new Date()
}) => {
  const outstandingBalance = calculateLoanOutstandingBalance({
    loan,
    repayments,
    settlements,
    schedules,
    penaltyAmount,
    referenceDate
  });
  const isDebtRecovery = isDebtRecoveryLoan(loan, { repayments, settlements, schedules, referenceDate });
  const isDistress = isDistressUnitLoan(loan, { outstandingBalance, referenceDate });
  if (!isDebtRecovery && !isDistress) {
    throw new Error("Only D.R.U or D.U loans can be renewed.");
  }
  if (!Number.isInteger(period) || period < 1 || period > 120) {
    throw new Error("Enter a loan period between 1 and 120 whole months.");
  }
  if (!schedules.length || schedules.length !== Number(loan.period)) {
    throw new Error("Repair the existing repayment schedule before renewing this loan.");
  }
  const installmentNumbers = new Set(schedules.map((row) => Number(row.installment_no)));
  if (schedules.some((row) => !Number.isFinite(businessDay(row.due_date)) || !(Number(row.amount) > 0)) || !Array.from({ length: schedules.length }, (_, index) => index + 1).every((number) => installmentNumbers.has(number))) {
    throw new Error("Repair invalid or duplicate installments before renewing this loan.");
  }
  const renewalBase = money(outstandingBalance);
  if (renewalBase <= 0) throw new Error("This loan has no valid outstanding balance to renew.");
  const interestRate = requestedInterestRate === void 0 ? 20 : Number(requestedInterestRate);
  if (!Number.isFinite(interestRate) || interestRate < 0 || interestRate > 100) {
    throw new Error("Enter an interest rate between 0% and 100%.");
  }
  const interest = money(renewalBase * interestRate / 100);
  const calendarDate = (value) => new Date(businessDay(value) * 864e5 + 12 * 36e5).toISOString();
  const fines = money(calculateLoanPenaltyState({
    schedules: schedules.map((row) => __spreadProps(__spreadValues({}, row), { due_date: calendarDate(row.due_date) })),
    repayments,
    settlements,
    penaltyAmount,
    referenceDate: calendarDate(referenceDate),
    useRecordedSchedulePaid: false
  }).outstandingFine);
  const renewedLiability = money(renewalBase + interest);
  const renewalBusinessDay = businessDay(requestedRenewalDate || referenceDate);
  if (!Number.isFinite(renewalBusinessDay)) throw new Error("Enter a valid restart date.");
  const renewalDate = new Date(renewalBusinessDay * 864e5 - 3 * 36e5).toISOString();
  const renewalDay = new Date(renewalBusinessDay * 864e5).toISOString().slice(0, 10);
  const defaultFinalDueDate = addMonthsPreservingDay(`${renewalDay}T12:00:00Z`, period);
  const finalDueBusinessDay = businessDay(requestedFinalDueDate || defaultFinalDueDate);
  const penultimateDueDate = period > 1 ? addMonthsPreservingDay(`${renewalDay}T12:00:00Z`, period - 1) : /* @__PURE__ */ new Date(`${renewalDay}T12:00:00Z`);
  if (!Number.isFinite(finalDueBusinessDay) || finalDueBusinessDay <= businessDay(penultimateDueDate)) {
    throw new Error("Final due date must be after the prior installment and restart date.");
  }
  const finalDueDate = new Date(finalDueBusinessDay * 864e5 + 12 * 36e5).toISOString();
  const monthlyCents = Math.floor(Math.round(renewedLiability * 100) / period);
  const installments = Array.from({ length: period }, (_, index) => ({
    loan: loan.id,
    installment_no: index + 1,
    due_date: index === period - 1 ? finalDueDate : addMonthsPreservingDay(`${renewalDay}T12:00:00Z`, index + 1).toISOString(),
    amount: (index === period - 1 ? Math.round(renewedLiability * 100) - monthlyCents * (period - 1) : monthlyCents) / 100,
    paid: 0,
    status: "pending",
    penalty_waived: false,
    carried_fine: 0
  }));
  const newLoanNo = getRenewedLoanNumber(loan.loan_no);
  const fingerprint = JSON.stringify({
    updated: loan.updated,
    newLoanNo,
    renewalDate,
    finalDueDate,
    period,
    renewalBase,
    interestRate,
    interest,
    fines,
    schedules: schedules.map((s) => [s.id, s.updated, s.amount, s.paid, s.due_date, s.penalty_waived, s.carried_fine])
  });
  return {
    principal: renewalBase,
    renewalBase,
    interestRate,
    interest,
    fines,
    liability: renewedLiability,
    amountDue: renewalBase,
    renewedAmount: renewedLiability,
    totalPayable: renewedLiability,
    decisionVerdict: "Renewed",
    newLoanNo,
    sourceLoanId: loan.id,
    sourceLoanNo: loan.loan_no,
    sourceUnit: isDebtRecovery ? "dru" : "du",
    period,
    renewalDate,
    finalDueDate,
    installments,
    fingerprint
  };
};
