// Generated by scripts/build_recovery_hook.mjs. Do not edit manually.
var __defProp = Object.defineProperty;
var __defProps = Object.defineProperties;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropDescs = Object.getOwnPropertyDescriptors;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getOwnPropSymbols = Object.getOwnPropertySymbols;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __propIsEnum = Object.prototype.propertyIsEnumerable;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __spreadValues = (a, b) => {
  for (var prop in b || (b = {}))
    if (__hasOwnProp.call(b, prop))
      __defNormalProp(a, prop, b[prop]);
  if (__getOwnPropSymbols)
    for (var prop of __getOwnPropSymbols(b)) {
      if (__propIsEnum.call(b, prop))
        __defNormalProp(a, prop, b[prop]);
    }
  return a;
};
var __spreadProps = (a, b) => __defProps(a, __getOwnPropDescs(b));
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/core/debtRecovery.js
var debtRecovery_exports = {};
__export(debtRecovery_exports, {
  buildDebtRecoveryRenewal: () => buildDebtRecoveryRenewal,
  getRecoveryAgeDays: () => getRecoveryAgeDays,
  isDebtRecoveryLoan: () => isDebtRecoveryLoan
});
module.exports = __toCommonJS(debtRecovery_exports);

// src/core/loanPenalty.js
var toDate = (value) => new Date(typeof value === "string" ? value.replace(" ", "T") : value);
var startOfLocalDay = (date = /* @__PURE__ */ new Date()) => {
  const value = toDate(date);
  if (Number.isNaN(value.getTime())) return null;
  value.setHours(0, 0, 0, 0);
  return value;
};
var endOfLocalDay = (date = /* @__PURE__ */ new Date()) => {
  const value = toDate(date);
  if (Number.isNaN(value.getTime())) return null;
  value.setHours(23, 59, 59, 999);
  return value;
};
var sortSchedules = (schedules = []) => schedules.slice().sort((a, b) => {
  const installmentDiff = (Number(a.installment_no) || 0) - (Number(b.installment_no) || 0);
  if (installmentDiff !== 0) return installmentDiff;
  return toDate(a.due_date || 0) - toDate(b.due_date || 0);
});
var sortRepayments = (repayments = []) => repayments.slice().sort((a, b) => toDate(a.date || a.created || 0) - toDate(b.date || b.created || 0));
var getContractPaymentDate = (record) => (record == null ? void 0 : record.date) || (record == null ? void 0 : record.effective_date) || (record == null ? void 0 : record.created) || /* @__PURE__ */ new Date();
var getRepaymentPrincipalAmount = (repayment) => Math.max(
  0,
  (Number(repayment == null ? void 0 : repayment.amount) || 0) - (Number(repayment == null ? void 0 : repayment.fine_amount) || 0)
);
var getContractSettlementAmount = (record) => {
  if ((record == null ? void 0 : record.settlement_kind) === "balance_off") return Math.max(0, Number(record.amount) || 0);
  return getRepaymentPrincipalAmount(record);
};
var calculateLoanPenaltyState = ({
  schedules = [],
  repayments = [],
  settlements = [],
  penaltyAmount = 0,
  referenceDate = /* @__PURE__ */ new Date(),
  useRecordedSchedulePaid = true
} = {}) => {
  const orderedSchedules = sortSchedules(schedules).map((schedule) => ({
    schedule,
    amount: Number(schedule.amount) || 0,
    paid: 0,
    completedAt: null
  }));
  sortRepayments([
    ...repayments,
    ...settlements.filter((settlement) => (settlement == null ? void 0 : settlement.status) !== "reversed").map((settlement) => __spreadProps(__spreadValues({}, settlement), {
      date: settlement.effective_date || settlement.date || settlement.created,
      settlement_kind: "balance_off"
    }))
  ]).forEach((repayment) => {
    let remainingPayment = getContractSettlementAmount(repayment);
    const paidAt = toDate(getContractPaymentDate(repayment));
    for (const item of orderedSchedules) {
      if (remainingPayment <= 0) break;
      const openAmount = Math.max(0, item.amount - item.paid);
      if (openAmount <= 0) continue;
      const applied = Math.min(openAmount, remainingPayment);
      item.paid += applied;
      remainingPayment -= applied;
      if (item.paid >= item.amount && !item.completedAt) item.completedAt = paidAt;
    }
  });
  if (useRecordedSchedulePaid) {
    orderedSchedules.forEach((item) => {
      const recordedPaid = Number(item.schedule.paid) || 0;
      if (recordedPaid > item.paid) item.paid = Math.min(item.amount, recordedPaid);
    });
  }
  const today = startOfLocalDay(referenceDate);
  const scheduleStates = orderedSchedules.map((item) => {
    const dueStart = startOfLocalDay(item.schedule.due_date);
    const dueEnd = endOfLocalDay(item.schedule.due_date);
    const dueDatePassed = Boolean(dueStart && today && dueStart < today);
    const completedLate = Boolean(item.completedAt && dueEnd && item.completedAt > dueEnd);
    const stillUnpaidAfterDue = item.paid < item.amount && dueDatePassed;
    const penaltyGenerated = Boolean(
      !item.schedule.penalty_waived && penaltyAmount > 0 && dueDatePassed && (completedLate || stillUnpaidAfterDue)
    );
    return {
      schedule: item.schedule,
      paid: item.paid,
      remainingPrincipal: Math.max(0, item.amount - item.paid),
      completedAt: item.completedAt,
      penaltyGenerated,
      penaltyAmount: (penaltyGenerated ? penaltyAmount : 0) + Math.max(0, Number(item.schedule.carried_fine) || 0)
    };
  });
  const generatedFineTotal = scheduleStates.reduce((sum, item) => sum + item.penaltyAmount, 0);
  const fineCollected = repayments.reduce((sum, repayment) => sum + (Number(repayment.fine_amount) || 0), 0);
  const principalPaid = [
    ...repayments,
    ...settlements.filter((settlement) => (settlement == null ? void 0 : settlement.status) !== "reversed").map((settlement) => __spreadProps(__spreadValues({}, settlement), { settlement_kind: "balance_off" }))
  ].reduce((sum, repayment) => sum + getContractSettlementAmount(repayment), 0);
  return {
    scheduleStates,
    generatedFineTotal,
    fineCollected,
    outstandingFine: Math.max(0, generatedFineTotal - fineCollected),
    principalPaid
  };
};

// src/core/loanPortfolio.js
var isCollectibleLoanRecord = (loan) => Boolean(loan == null ? void 0 : loan.disbursement_date) && ["disbursed", "approved", "partial_approved"].includes(loan == null ? void 0 : loan.status);

// src/core/repaymentSchedule.js
var toValidDate = (value) => {
  if (!value) return null;
  const date = new Date(typeof value === "string" ? value.replace(" ", "T") : value);
  return Number.isNaN(date.getTime()) ? null : date;
};
var addMonthsPreservingDay = (dateInput, monthsToAdd) => {
  const source = toValidDate(dateInput) || /* @__PURE__ */ new Date();
  const targetDay = source.getDate();
  const dueDate = new Date(source);
  dueDate.setDate(1);
  dueDate.setMonth(dueDate.getMonth() + monthsToAdd);
  const lastDayOfTargetMonth = new Date(
    dueDate.getFullYear(),
    dueDate.getMonth() + 1,
    0
  ).getDate();
  dueDate.setDate(Math.min(targetDay, lastDayOfTargetMonth));
  return dueDate;
};

// src/core/debtRecovery.js
var money = (value) => Math.round((Number(value) || 0) * 100) / 100;
var businessDay = (value) => {
  const date = new Date(typeof value === "string" ? value.replace(" ", "T") : value);
  return Number.isNaN(date.getTime()) ? NaN : Math.floor((date.getTime() + 3 * 36e5) / 864e5);
};
var getRecoveryAgeDays = (loan, referenceDate = /* @__PURE__ */ new Date()) => businessDay(referenceDate) - businessDay((loan == null ? void 0 : loan.renewal_date) || (loan == null ? void 0 : loan.disbursement_date));
var isDebtRecoveryLoan = (loan, {
  repayments = [],
  settlements = [],
  schedules = [],
  referenceDate = /* @__PURE__ */ new Date()
} = {}) => {
  if (!isCollectibleLoanRecord(loan) || getRecoveryAgeDays(loan, referenceDate) < 90) return false;
  if (!Number.isFinite(getRecoveryAgeDays(loan, referenceDate))) return false;
  if (!(Number(loan.total_liability) > 0)) return false;
  if (repayments.some((record) => !record.is_reversed && Number(record.amount) > 0)) return false;
  if (settlements.some((record) => record.status !== "reversed" && Number(record.amount) > 0)) return false;
  return !schedules.some((record) => Number(record.paid) > 0);
};
var buildDebtRecoveryRenewal = ({
  loan,
  repayments = [],
  settlements = [],
  schedules = [],
  penaltyAmount = 500,
  period,
  referenceDate = /* @__PURE__ */ new Date()
}) => {
  if (!isDebtRecoveryLoan(loan, { repayments, settlements, schedules, referenceDate })) {
    throw new Error("Only loans with no payments for at least 90 days can be renewed through D.R.U.");
  }
  if (!Number.isInteger(period) || period < 1 || period > 120) {
    throw new Error("Enter a loan period between 1 and 120 whole months.");
  }
  if (!schedules.length || schedules.length !== Number(loan.period)) {
    throw new Error("Repair the existing repayment schedule before renewing this loan.");
  }
  const installmentNumbers = new Set(schedules.map((row) => Number(row.installment_no)));
  if (schedules.some((row) => !Number.isFinite(businessDay(row.due_date)) || !(Number(row.amount) > 0)) || !Array.from({ length: schedules.length }, (_, index) => index + 1).every((number) => installmentNumbers.has(number))) {
    throw new Error("Repair invalid or duplicate installments before renewing this loan.");
  }
  const principal = money(loan.approved_amount || loan.amount_applied);
  if (principal <= 0) throw new Error("This loan has no valid principal to renew.");
  const interestRate = 20;
  const interest = money(principal * interestRate / 100);
  const calendarDate = (value) => new Date(businessDay(value) * 864e5 + 12 * 36e5).toISOString();
  const fines = money(calculateLoanPenaltyState({
    schedules: schedules.map((row) => __spreadProps(__spreadValues({}, row), { due_date: calendarDate(row.due_date) })),
    repayments,
    settlements,
    penaltyAmount,
    referenceDate: calendarDate(referenceDate)
  }).outstandingFine);
  const liability = money(principal + interest);
  const renewalDate = new Date(businessDay(referenceDate) * 864e5 - 3 * 36e5).toISOString();
  const renewalDay = new Date(businessDay(referenceDate) * 864e5).toISOString().slice(0, 10);
  const monthlyCents = Math.floor(Math.round(liability * 100) / period);
  const installments = Array.from({ length: period }, (_, index) => ({
    loan: loan.id,
    installment_no: index + 1,
    due_date: addMonthsPreservingDay(`${renewalDay}T12:00:00Z`, index + 1).toISOString(),
    amount: (index === period - 1 ? Math.round(liability * 100) - monthlyCents * (period - 1) : monthlyCents) / 100,
    paid: 0,
    status: "pending",
    penalty_waived: false,
    carried_fine: index === 0 ? fines : 0
  }));
  const fingerprint = JSON.stringify({
    updated: loan.updated,
    renewalDate,
    period,
    principal,
    interest,
    fines,
    schedules: schedules.map((s) => [s.id, s.updated, s.amount, s.paid, s.due_date, s.penalty_waived, s.carried_fine])
  });
  return {
    principal,
    interestRate,
    interest,
    fines,
    liability,
    totalPayable: money(liability + fines),
    period,
    renewalDate,
    installments,
    fingerprint
  };
};
