import { build } from 'esbuild';

await build({
  entryPoints: ['src/core/debtRecovery.js'],
  outfile: 'pb_hooks/lib/debtRecovery.js',
  bundle: true,
  platform: 'neutral',
  format: 'cjs',
  target: 'es2015',
  banner: { js: '// Generated by scripts/build_recovery_hook.mjs. Do not edit manually.' }
});
